In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics

In [2]:
df = pd.read_csv("ImportantValues.RNA.csv",sep=';', decimal=',')
df

PatientID  Tumor            EIF2AK1     CSTF2  \
0    TCGA-05-4244-01A-01R-1107-07      1          6818.1098  772.1442   
1    TCGA-05-4249-01A-01R-1107-07      1          3346.7627  494.8475   
2    TCGA-05-4250-01A-01R-1107-07      1          5447.9085  677.4434   
3    TCGA-05-4382-01A-01R-1206-07      1          6730.5776  421.6539   
4    TCGA-05-4384-01A-01R-1755-07      1  5373.090999999999  364.0806   
..                            ...    ...                ...       ...   
569  TCGA-91-6831-11A-02R-1858-07      0          2415.8713  188.6792   
570  TCGA-91-6835-11A-01R-1858-07      0          3258.6457  249.2684   
571  TCGA-91-6836-11A-01R-1858-07      0          2776.9988  180.4839   
572  TCGA-91-6847-11A-01R-1949-07      0          2952.1629     200.0   
573  TCGA-91-6849-11A-01R-1949-07      0          2569.0418  214.2757   

       GORASP2      IRAK1       SNX1             C13orf1      KIF1C  \
0     2348.547  4379.7888  1655.9909            234.2264  1515.3155   
1    5591.7444  1324.8519  2624.5912            200.2571  2713.1293   
2    3943.2977  3398.1597  1827.0745            318.3288  3529.1387   
3    3877.4452  5879.9423  2234.3829            285.9685  4327.5763   
4    3034.2089  2764.8137  3251.6799  362.24800000000005  4911.4233   
..         ...        ...        ...                 ...        ...   
569  1479.4673  1002.2198  4497.2253            751.3873  6762.4861   
570  1822.5403  1630.2654  3695.8111            379.5393   4647.791   
571  1733.7394  1388.3979  4187.0704            613.3328  6153.6418   
572  1902.2624  1334.8416  4635.2941            925.7919  9858.8235   
573  1518.5628  1376.4887  4198.5622            951.0427  7616.8812   

          GARS  ...     ARL13B      ALG6    TRIM35     PTCD1     STARD7  \
0    2435.8146  ...   233.8773  371.4111  268.4353  365.3443  4562.4575   
1     1569.861  ...   202.5108  222.7941  471.6666  308.6535  3337.9185   
2    3322.8882  ...   270.9111  161.8171  402.2217  438.2293  3135.6147   
3    2248.5018  ...   391.7409  274.0033  346.5124  455.6136  2852.5892   
4     1966.402  ...   166.7685  209.5296  472.8161   403.934  3010.5559   
..         ...  ...        ...       ...       ...       ...        ...   
569  1358.4906  ...  1032.1865  168.7014  398.4462  190.4772  5005.7381   
570   1252.605  ...   479.1214  154.0704  462.8376  278.9176  4172.2457   
571  1283.7016  ...   448.4752  192.2036  388.3139  247.3333  4787.2458   
572  1237.1041  ...   593.6652  143.8914  565.6109  303.0769  7069.6742   
573  1102.4331  ...   593.9164  161.4832   481.344  219.0814  5703.3756   

         NKRF     APH1B    HSD17B4     NPLOC4    HSP90AB1  
0    559.5602  121.8256   2452.221   4543.852  30568.8105  
1    379.9089  266.5802  1916.2864  3059.8767   33322.521  
2    443.6707  347.5089  1464.9755  3358.3686  34958.7996  
3    160.5731  421.4146  1980.2419  4312.9787  21074.0808  
4    222.9688  448.3812  3263.8974  4005.4979  18775.8094  
..        ...       ...        ...        ...         ...  
569  243.0633  589.3452  4625.9711   1654.828  18588.2353  
570  226.0952  616.2817  2688.0904  2113.1447  22259.4176  
571  245.3331  737.5619  4787.9021  2144.7114  17821.8093  
572  229.8643  607.2398  4186.4253  2135.7466  21454.2986  
573  180.1158  588.4819   3278.574  2214.1826  15956.5548  

[574 rows x 102 columns]

In [3]:
X = df.iloc[:, 2:].values
Y = df.iloc[:, 1:2].values
#splaszczenie listy
Y = np.ravel(Y)

In [4]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

In [5]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
rfc = RandomForestClassifier()
rfc.fit(X_train,Y_train)# predictions
rfc_predict = rfc.predict(X_test)
rfc_predict

C:\Users\Macie\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


array([1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [7]:
rfc_cv_score = cross_val_score(rfc, X, Y, cv=10, scoring='roc_auc')
rfc_cv_score

array([1.        , 1.        , 1.        , 0.99839744, 1.        ,
       1.        , 1.        , 0.9869281 , 1.        , 0.99019608])

In [8]:
print("=== Confusion Matrix ===")
print(confusion_matrix(Y_test, rfc_predict))
print("=== Classification Report ===")
print(classification_report(Y_test, rfc_predict))
print("=== All AUC Scores ===")
print(rfc_cv_score)
print("=== Mean AUC Score ===")
print("Mean AUC Score - Random Forest: ", rfc_cv_score.mean())

=== Confusion Matrix ===
[[ 15   3]
 [  1 154]]
=== Classification Report ===
              precision    recall  f1-score   support

           0       0.94      0.83      0.88        18
           1       0.98      0.99      0.99       155

    accuracy                           0.98       173
   macro avg       0.96      0.91      0.93       173
weighted avg       0.98      0.98      0.98       173

=== All AUC Scores ===
[1.         1.         1.         0.99839744 1.         1.
 1.         0.9869281  1.         0.99019608]
=== Mean AUC Score ===
Mean AUC Score - Random Forest:  0.9975521618903972


In [9]:
print("Accuracy:",metrics.accuracy_score(Y_test, rfc_predict))

Accuracy: 0.976878612716763
